language: java
jdk: openjdk11

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg2 --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg2 --import-ownertrust
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn -B -X release:prepare release:perform

deploy:
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    on:
      repo: "${TRAVIS_REPO_SLUG}"
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*
