env:
  global:
    - secure: ""
    - secure: ""

language: java
jdk: openjdk11

script:
  - mvn -B release:prepare

before_deploy:
  - mvn -B release:perform

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: "target/*.jar"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE = *"MAKE_RELEASE"*